### ISSUE TITLE
Module 'DCM' not found

### ISSUE THREAD

**Issue by edgarriba** [ros-aldebaran/nao_dcm_robot#1]
When I launch:
roslaunch nao_dcm_bringup nao_dcm_H25_bringup_remote.launch

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[nao_dcm/nao_trajectory_controller-1]: started with pid [11650]
process[robot_state_publisher-2]: started with pid [11653]
/opt/ros/indigo/lib/robot_state_publisher/robot_state_publisher
process[nao_dcm_driver-3]: started with pid [11677]
[INFO ] Starting ALNetwork
[INFO] [WallTime: 1413359766.914217] Controller Spawner: Waiting for service controller_manager/load_controller
[INFO ] Nao Driver Broker is listening on 127.0.0.1:54022
[INFO ] Starting ALNetwork
[INFO ] NAOqi is listening on 127.0.0.1:54021
terminate called after throwing an instance of 'AL::ALError'
  what():  	ALProxy::constructor
	Module 'DCM' not found.
[nao_dcm_driver-3] process has died [pid 11677, exit code -6, cmd /home/eriba/catkin_ws/devel/lib/nao_dcm_driver/nao_dcm_driver /joint_states:=/nao_dcm/joint_states /controller_manager:=/nao_dcm/controller_manager __name:=nao_dcm_driver __log:=/home/eriba/.ros/log/fcb34d12-5438-11e4-b145-dc85de44e863/nao_dcm_driver-3.log].
log file: /home/eriba/.ros/log/fcb34d12-5438-11e4-b145-dc85de44e863/nao_dcm_driver-3*.log
[WARN] [WallTime: 1413359797.181925] Controller Spawner couldn't find the expected controller_manager ROS interface.
[nao_dcm/nao_trajectory_controller-1] process has finished cleanly
log file: /home/eriba/.ros/log/fcb34d12-5438-11e4-b145-dc85de44e863/nao_dcm-nao_trajectory_controller-1*.log

**Comment by vrabaud** [comment]
shall we close that one then ?

**Comment by edgarriba** [comment]
sure!
