### ISSUE TITLE
Fail to load /nao_dcm controllers

### ISSUE THREAD

**Issue by Yanzqing** [ros-aldebaran/nao_dcm_robot#12]
When I launch   $ roslaunch nao_dcm_bringup nao_dcm_H25_bringup_remote.launch
[WARN] [WallTime: 1464757770.251003] Controller Spawner couldn't find the expected controller_manager ROS interface.
So I add     
     remap from="/joint_states" to="/nao_dcm/joint_states"
     remap from="/controller_manager" to="/nao_dcm/controller_manager"

to node nao_dcm_driver. But I get error:
[ INFO] [1464758119.769550454]: Nao Module loaded succesfully!
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/controller_manager/spawner", line 212, in <module>
    if __name__ == '__main__': main()
  File "/opt/ros/indigo/lib/controller_manager/spawner", line 204, in main
    resp = switch_controller(loaded, [], 2)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 525, in call
    raise ServiceException("transport error completing service call: %s"%(str(e)))
rospy.service.ServiceException: transport error completing service call: unable to receive data from sender, check sender's logs for details
[INFO] [WallTime: 1464758119.915878] Shutting down spawner. Stopping and unloading controllers...
[nao_dcm_driver-5] process has died [pid 9008, exit code -11, cmd /home/exbot/My_packages/Nao/Nao_DCM/devel/lib/nao_dcm_driver/nao_dcm_driver /controller_manager:=/nao_dcm/controller_manager __name:=nao_dcm_driver __log:=/home/exbot/.ros/log/d38cb410-27b7-11e6-8b29-b8975ac1ee5a/nao_dcm_driver-5.log].
log file: /home/exbot/.ros/log/d38cb410-27b7-11e6-8b29-b8975ac1ee5a/nao_dcm_driver-5*.log
[WARN] [WallTime: 1464758150.916755] Controller Spawner couldn't reach controller_manager to take down controllers. Waited for 30 second(s).
[nao_dcm/nao_trajectory_controller-3] process has died [pid 9005, exit code 1, cmd /opt/ros/indigo/lib/controller_manager/spawner /nao_dcm/Head_controller /nao_dcm/RightArm_controller /nao_dcm/LeftArm_controller /nao_dcm/LeftLeg_controller /nao_dcm/RightLeg_controller /nao_dcm/RightHand_controller /nao_dcm/LeftHand_controller /nao_dcm/Pelvis_controller /nao_dcm/LeftFoot_controller /nao_dcm/RightFoot_controller /nao_dcm/joint_state_controller __name:=nao_trajectory_controller __log:=/home/exbot/.ros/log/d38cb410-27b7-11e6-8b29-b8975ac1ee5a/nao_dcm-nao_trajectory_controller-3.log].
log file: /home/exbot/.ros/log/d38cb410-27b7-11e6-8b29-b8975ac1ee5a/nao_dcm-nao_trajectory_controller-3*.log

How can I solve this problem?  Thank you !

**Comment by nlyubova** [comment]
hi, why do you need to remap them?
