### ISSUE TITLE
nao_dcm_driver process died

### ISSUE THREAD

**Issue by edgarriba** [ros-aldebaran/nao_dcm_robot#2]
I'm on real robot.

1) Uncomment dcm_hal on autoload.ini
2) set robot ip (192.168.0.108) on nao_dcm.yaml
3)  `roslaunch nao_dcm_bringup nao_dcm_H25_bringup_remote.launch` 

I get the following:

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[nao_dcm/nao_trajectory_controller-1]: started with pid [6564]
process[robot_state_publisher-2]: started with pid [6568]
/opt/ros/indigo/lib/robot_state_publisher/robot_state_publisher
process[nao_dcm_driver-3]: started with pid [6591]
[INFO ] Starting ALNetwork
[INFO] [WallTime: 1413545350.459857] Controller Spawner: Waiting for service controller_manager/load_controller
[INFO ] Nao Driver Broker is listening on 192.168.0.116:54022
[INFO ] Starting ALNetwork
[INFO ] NAOqi is listening on 127.0.0.1:54010
[INFO ] Starting Nao
[nao_dcm_driver-3] process has died [pid 6591, exit code -11, cmd /home/eriba/catkin_ws/devel/lib/nao_dcm_driver/nao_dcm_driver /joint_states:=/nao_dcm/joint_states /controller_manager:=/nao_dcm/controller_manager __name:=nao_dcm_driver __log:=/home/eriba/.ros/log/161a378a-55eb-11e4-9c77-dc85de44e863/nao_dcm_driver-3.log].
log file: /home/eriba/.ros/log/161a378a-55eb-11e4-9c77-dc85de44e863/nao_dcm_driver-3*.log
^C[robot_state_publisher-2] killing on exit
[nao_dcm/nao_trajectory_controller-1] killing on exit
[WARN] [WallTime: 1413545375.342409] Controller Spawner couldn't find the expected controller_manager ROS interface.
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by vrabaud** [comment]
shall we close that then ?

**Comment by nlyubova** [comment]
Seams good!

**Comment by edgarriba** [comment]
:+1:

**Comment by filipposanfilippo** [comment]
Hi, I am having the same issue with Jade. 'Controller Spawner couldn't find the expected controller_manager ROS interface.'

Any suggestions?

**Comment by mikaelarguedas** [comment]
Hi @filipposanfilippo,
Could you give us more information about your setup ? (ubuntu version, nao_dcm package version, install from source or binaries).
And more importantly could you provide the following informations:
 * Do you have a real NAO to test the code on ?
 * What command did you run? 
 * What nodes are running ?
 * The result of a `rostopic list`
 * A log of your console showing the node dying and the previous and next ~20lines.

Thanks!

**Comment by filipposanfilippo** [comment]
- Unfortunately, I do not have a real NAO to test the code on.

- I have a modified version of the rrbot model, I have added one link and one joint. I first started my simulation with 'rroslaunch rrbot_gazebo rrbot_world.launch'. The output is the follow:
`... logging to /home/parallels/.ros/log/50f2e05a-0797-11e6-80b8-001c42fc65da/roslaunch-ubuntu-23239.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

Traditional processing is deprecated. Switch to --inorder processing!
To check for compatibility of your document, use option --check-order.
For more infos, see http://wiki.ros.org/xacro#Processing_Order
xacro.py is deprecated; please use xacro instead
started roslaunch server http://ubuntu:40337/

SUMMARY
========

PARAMETERS
 * /robot_description: <?xml version="1....
 * /rosdistro: jade
 * /rosversion: 1.11.16
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    urdf_spawner (gazebo_ros/spawn_model)

auto-starting new master
process[master]: started with pid [23254]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 50f2e05a-0797-11e6-80b8-001c42fc65da
process[rosout-1]: started with pid [23270]
started core service [/rosout]
process[gazebo-2]: started with pid [23281]
process[gazebo_gui-3]: started with pid [23287]
process[urdf_spawner-4]: started with pid [23302]
[ INFO] [1461225717.276491634]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1461225717.279094916]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
spawn_model script started
[INFO] [WallTime: 1461225717.462060] [0.000000] Loading model xml from ros parameter
[INFO] [WallTime: 1461225717.465143] [0.000000] Waiting for service /gazebo/spawn_urdf_model
[INFO] [WallTime: 1461225718.372957] [0.000000] Calling service /gazebo/spawn_urdf_model
[ INFO] [1461225718.383535894, 0.023000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[INFO] [WallTime: 1461225718.576297] [0.135000] Spawn status: SpawnModel: Successfully spawned model
[ INFO] [1461225718.599593230, 0.147000000]: Physics dynamic reconfigure ready.
[urdf_spawner-4] process has finished cleanly
log file: /home/parallels/.ros/log/50f2e05a-0797-11e6-80b8-001c42fc65da/urdf_spawner-4*.log`

Here is the log:
`[rospy.client][INFO] 2016-04-21 10:01:57,345: init_node, name[/urdf_spawner], pid[23302]
[xmlrpc][INFO] 2016-04-21 10:01:57,345: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2016-04-21 10:01:57,346: Started XML-RPC server [http://ubuntu:33038/]
[rospy.impl.masterslave][INFO] 2016-04-21 10:01:57,346: _ready: http://ubuntu:33038/
[rospy.init][INFO] 2016-04-21 10:01:57,346: ROS Slave URI: [http://ubuntu:33038/]
[xmlrpc][INFO] 2016-04-21 10:01:57,348: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2016-04-21 10:01:57,350: Registering with master node http://localhost:11311
[rospy.init][INFO] 2016-04-21 10:01:57,448: registered with master
[rospy.rosout][INFO] 2016-04-21 10:01:57,449: initializing /rosout core topic
[rospy.rosout][INFO] 2016-04-21 10:01:57,452: connected to core topic /rosout
[rospy.simtime][INFO] 2016-04-21 10:01:57,454: initializing /clock core topic
[rospy.simtime][INFO] 2016-04-21 10:01:57,458: connected to core topic /clock
[rosout][INFO] 2016-04-21 10:01:57,462: Loading model xml from ros parameter
[rosout][INFO] 2016-04-21 10:01:57,465: Waiting for service /gazebo/spawn_urdf_model
[rospy.internal][INFO] 2016-04-21 10:01:57,635: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2016-04-21 10:01:58,372: Calling service /gazebo/spawn_urdf_model
[rospy.internal][INFO] 2016-04-21 10:01:58,381: topic[/clock] adding connection to [http://ubuntu:35949/], count 0
[rosout][INFO] 2016-04-21 10:01:58,576: Spawn status: SpawnModel: Successfully spawned model
[rospy.core][INFO] 2016-04-21 10:01:58,576: signal_shutdown [atexit]
[rospy.internal][INFO] 2016-04-21 10:01:58,579: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-04-21 10:01:58,579: topic[/clock] removing connection to http://ubuntu:35949/
[rospy.impl.masterslave][INFO] 2016-04-21 10:01:58,580: atexit`


Then, I use the command 'roslaunch rrbot_control rrbot_control.launch'. The output is the following:
`... logging to /home/parallels/.ros/log/bdd5430c-0797-11e6-8745-001c42fc65da/roslaunch-ubuntu-24962.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ubuntu:35458/

SUMMARY
========

PARAMETERS
 * /rosdistro: jade
 * /rosversion: 1.11.16
 * /rrbot/joint1_position_controller/joint: joint1
 * /rrbot/joint1_position_controller/pid/d: 10.0
 * /rrbot/joint1_position_controller/pid/i: 0.01
 * /rrbot/joint1_position_controller/pid/p: 100.0
 * /rrbot/joint1_position_controller/type: effort_controller...
 * /rrbot/joint2_position_controller/joint: joint2
 * /rrbot/joint2_position_controller/pid/d: 10.0
 * /rrbot/joint2_position_controller/pid/i: 0.01
 * /rrbot/joint2_position_controller/pid/p: 100.0
 * /rrbot/joint2_position_controller/type: effort_controller...
 * /rrbot/joint3_position_controller/joint: joint3
 * /rrbot/joint3_position_controller/pid/d: 10.0
 * /rrbot/joint3_position_controller/pid/i: 0.01
 * /rrbot/joint3_position_controller/pid/p: 100.0
 * /rrbot/joint3_position_controller/type: effort_controller...
 * /rrbot/joint_state_controller/publish_rate: 50
 * /rrbot/joint_state_controller/type: joint_state_contr...

NODES
  /
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
  /rrbot/
    controller_spawner (controller_manager/spawner)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[rrbot/controller_spawner-1]: started with pid [24983]
process[robot_state_publisher-2]: started with pid [24984]
[INFO] [WallTime: 1461225968.233102] [0.000000] Controller Spawner: Waiting for service controller_manager/load_controller
[WARN] [WallTime: 1461225998.446063] [94.534000] Controller Spawner couldn't find the expected controller_manager ROS interface.
[rrbot/controller_spawner-1] process has finished cleanly
log file: /home/parallels/.ros/log/bdd5430c-0797-11e6-8745-001c42fc65da/rrbot-controller_spawner-1*.log`

Here is the log:
`[rospy.client][INFO] 2016-04-21 10:06:08,118: init_node, name[/rrbot/controller_spawner], pid[24983]
[xmlrpc][INFO] 2016-04-21 10:06:08,120: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2016-04-21 10:06:08,120: Started XML-RPC server [http://ubuntu:46581/]
[rospy.impl.masterslave][INFO] 2016-04-21 10:06:08,120: _ready: http://ubuntu:46581/
[rospy.init][INFO] 2016-04-21 10:06:08,121: ROS Slave URI: [http://ubuntu:46581/]
[rospy.registration][INFO] 2016-04-21 10:06:08,122: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2016-04-21 10:06:08,122: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2016-04-21 10:06:08,221: registered with master
[rospy.rosout][INFO] 2016-04-21 10:06:08,222: initializing /rosout core topic
[rospy.rosout][INFO] 2016-04-21 10:06:08,224: connected to core topic /rosout
[rospy.simtime][INFO] 2016-04-21 10:06:08,226: initializing /clock core topic
[rospy.simtime][INFO] 2016-04-21 10:06:08,229: connected to core topic /clock
[rosout][INFO] 2016-04-21 10:06:08,233: Controller Spawner: Waiting for service controller_manager/load_controller
[rospy.internal][INFO] 2016-04-21 10:06:08,239: topic[/clock] adding connection to [http://ubuntu:44472/], count 0
[rospy.internal][INFO] 2016-04-21 10:06:08,499: topic[/rosout] adding connection to [/rosout], count 0
[rosout][WARNING] 2016-04-21 10:06:38,446: Controller Spawner couldn't find the expected controller_manager ROS interface.
[rospy.core][INFO] 2016-04-21 10:06:38,446: signal_shutdown [atexit]
[rospy.internal][INFO] 2016-04-21 10:06:38,451: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-04-21 10:06:38,451: topic[/clock] removing connection to http://ubuntu:44472/
[rospy.impl.masterslave][INFO] 2016-04-21 10:06:38,451: atexit
[rospy.internal][ERROR] 2016-04-21 10:06:38,452: Traceback (most recent call last):
  File "/opt/ros/jade/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 698, in receive_once
    self.stat_bytes += recv_buff(sock, b, p.buff_size)
  File "/opt/ros/jade/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 103, in recv_buff
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer`

- The result of 'rostopic list' is:
`/clock
/gazebo/link_states
/gazebo/model_states
/gazebo/parameter_descriptions
/gazebo/parameter_updates
/gazebo/set_link_state
/gazebo/set_model_state
/rosout
/rosout_agg`

I hope I managed to answer your question. Thank you for your time and help!

**Comment by mikaelarguedas** [comment]
This seems to be a non naoqi robot related question.
Could you please refer to ROS Answers, I do think that there are several threads addressing this particular issue.

If you want to simulate a NAO I would advise you to use the [nao_gazebo_plugin](https://github.com/ros-naoqi/nao_virtual/tree/master/nao_gazebo_plugin/) package
